"""
GraphRAG settings.yaml ジェネレーター
=====================================
対話式インストーラーから呼び出され、ユーザーの選択に基づいて
settings.yaml と .env を生成する。

使用方法:
  python3 generate_settings.py --config config.json --output-dir /path/to/project
"""

import argparse
import json
import os
import sys


SETTINGS_TEMPLATE = """\
### GraphRAG Hybrid Settings
### Generated by graphrag-hybrid-installer
### LLM: {llm_provider} / Embedding: {embedding_provider}
### NLP: {nlp_mode} mode

### LLM settings ###
completion_models:
  default_completion_model:
    model_provider: {llm_model_provider}
    model: {llm_model}
    auth_method: api_key
    api_key: ${{GRAPHRAG_API_KEY}}
{llm_api_base}{llm_api_version}    retry:
      type: exponential_backoff
    concurrent_requests: {llm_concurrent}
    tokens_per_minute: {llm_tpm}
    requests_per_minute: {llm_rpm}

embedding_models:
  default_embedding_model:
    model_provider: {embedding_model_provider}
    model: {embedding_model}
    api_base: {embedding_api_base}
    auth_method: api_key
    api_key: ${{GRAPHRAG_EMBEDDING_KEY}}
{embedding_api_version}    retry:
      type: exponential_backoff
    concurrent_requests: {embedding_concurrent}
    batch_size: {embedding_batch_size}

### Document processing settings ###
input:
  type: text
  file_pattern: ".*\\\\.md$$"

chunking:
  type: tokens
  size: {chunk_size}
  overlap: {chunk_overlap}
  encoding_model: o200k_base

### Storage settings ###
input_storage:
  type: file
  base_dir: "{input_dir}"

output_storage:
  type: file
  base_dir: "output"

reporting:
  type: file
  base_dir: "logs"

cache:
  type: json
  storage:
    type: file
    base_dir: "cache"

vector_store:
  type: lancedb
  db_uri: output/lancedb
  vector_size: {vector_size}

### Workflow settings ###
embed_text:
  embedding_model_id: default_embedding_model

extract_graph:
  completion_model_id: default_completion_model
  prompt: "prompts/extract_graph.txt"
  entity_types: {entity_types}
  max_gleanings: 1

summarize_descriptions:
  completion_model_id: default_completion_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: syntactic_parser
    model_name: {nlp_mode}
    max_word_length: 20
    include_named_entities: true
    exclude_entity_tags: ["DATE", "TIME", "PERCENT", "MONEY", "QUANTITY", "ORDINAL", "CARDINAL"]
    exclude_pos_tags: ["DET", "PRON", "INTJ", "X", "ADP", "AUX", "CCONJ", "SCONJ", "PUNCT"]
    exclude_nouns: ["STUDY", "FIGURE", "INVESTIGATED", "MEASURED", "RESULTS", "INCREASE", "INCREASES", "OBTAINED", "OBSERVED", "SHOWN", "TABLE", "USED", "PERFORMED", "SPECIMEN", "SPECIMENS", "SAMPLE", "SAMPLES", "ANALYSIS", "METHOD", "COMPARISON", "DATA", "PROCESS", "CONDITION", "CONDITIONS", "EXPERIMENT", "MEASUREMENT", "APPLIED", "REGION", "VALUE", "VALUES", "CASE", "NUMBER", "RATE", "TIME", "RANGE", "DIRECTION", "AREA", "POSITION", "SIDE", "PART", "PRESENT", "SHOWS", "MATER", "TRANS", "ENG", "SCI", "J", "VOL", "PP", "NO"]
    word_delimiter: " "
  concurrent_requests: 25

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false
  completion_model_id: default_completion_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  completion_model_id: default_completion_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

snapshots:
  graphml: false
  embeddings: false

### Query settings ###
local_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  completion_model_id: default_completion_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"

basic_search:
  completion_model_id: default_completion_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
"""


# --- Provider presets ---

LLM_PRESETS = {
    "openai": {
        "llm_model_provider": "openai",
        "llm_model": "gpt-4o-mini",
        "llm_api_base": "",
        "llm_api_version": "",
        "llm_concurrent": 25,
        "llm_tpm": 150000,
        "llm_rpm": 500,
    },
    "azure": {
        "llm_model_provider": "azure_openai",
        "llm_model": "gpt-4o-mini",
        "llm_api_base": "    api_base: ${AZURE_OPENAI_ENDPOINT}\n",
        "llm_api_version": '    api_version: "2024-06-01"\n',
        "llm_concurrent": 25,
        "llm_tpm": 150000,
        "llm_rpm": 500,
    },
    "ollama": {
        "llm_model_provider": "openai",
        "llm_model": "qwen2.5:7b",
        "llm_api_base": "    api_base: ${OLLAMA_BASE_URL}\n",
        "llm_api_version": "",
        "llm_concurrent": 4,
        "llm_tpm": 999999,
        "llm_rpm": 999999,
    },
}

EMBEDDING_PRESETS = {
    "ollama_bge": {
        "embedding_model_provider": "openai",
        "embedding_model": "bge-m3",
        "embedding_api_base": "${OLLAMA_BASE_URL}",
        "embedding_api_version": "",
        "embedding_concurrent": 4,
        "embedding_batch_size": 8,
        "vector_size": 1024,
    },
    "openai_small": {
        "embedding_model_provider": "openai",
        "embedding_model": "text-embedding-3-small",
        "embedding_api_base": "https://api.openai.com/v1",
        "embedding_api_version": "",
        "embedding_concurrent": 25,
        "embedding_batch_size": 16,
        "vector_size": 1536,
    },
    "openai_large": {
        "embedding_model_provider": "openai",
        "embedding_model": "text-embedding-3-large",
        "embedding_api_base": "https://api.openai.com/v1",
        "embedding_api_version": "",
        "embedding_concurrent": 25,
        "embedding_batch_size": 16,
        "vector_size": 3072,
    },
    "azure": {
        "embedding_model_provider": "azure_openai",
        "embedding_model": "text-embedding-3-large",
        "embedding_api_base": "${AZURE_OPENAI_ENDPOINT}",
        "embedding_api_version": '    api_version: "2024-06-01"\n',
        "embedding_concurrent": 25,
        "embedding_batch_size": 16,
        "vector_size": 3072,
    },
}

NLP_PRESETS = {
    "hybrid": {"nlp_mode": "hybrid", "chunk_size": 800, "chunk_overlap": 80},
    "scispacy": {"nlp_mode": "scispacy", "chunk_size": 1200, "chunk_overlap": 100},
    "ginza": {"nlp_mode": "ginza", "chunk_size": 800, "chunk_overlap": 80},
}


def generate(config: dict, output_dir: str):
    """設定ファイルを生成"""
    os.makedirs(output_dir, exist_ok=True)

    # プリセットをマージ
    llm_preset = LLM_PRESETS.get(config["llm_provider"], LLM_PRESETS["openai"]).copy()
    emb_preset = EMBEDDING_PRESETS.get(config["embedding_provider"], EMBEDDING_PRESETS["ollama_bge"]).copy()
    nlp_preset = NLP_PRESETS.get(config["nlp_mode"], NLP_PRESETS["hybrid"]).copy()

    # ユーザーのカスタム値で上書き
    if config.get("llm_model"):
        llm_preset["llm_model"] = config["llm_model"]
    if config.get("ollama_url"):
        llm_preset["llm_api_base"] = f"    api_base: {config['ollama_url']}\n"
    if config.get("embedding_model"):
        emb_preset["embedding_model"] = config["embedding_model"]
    if config.get("ollama_url") and config["embedding_provider"] == "ollama_bge":
        emb_preset["embedding_api_base"] = config["ollama_url"]

    # テンプレート変数
    params = {
        **llm_preset,
        **emb_preset,
        **nlp_preset,
        "llm_provider": config["llm_provider"],
        "embedding_provider": config["embedding_provider"],
        "input_dir": config.get("input_dir", "input"),
        "entity_types": config.get(
            "entity_types",
            "[organization, person, geo, event, material, method, measurement, chemical_compound]"
        ),
    }

    # settings.yaml 生成
    settings_content = SETTINGS_TEMPLATE.format(**params)
    settings_path = os.path.join(output_dir, "settings.yaml")
    with open(settings_path, "w") as f:
        f.write(settings_content)
    print(f"✅ Generated: {settings_path}")

    # .env 生成
    env_lines = []
    if config["llm_provider"] == "openai":
        env_lines.append(f"GRAPHRAG_API_KEY={config.get('api_key', '<YOUR_OPENAI_API_KEY>')}")
        if config["embedding_provider"].startswith("openai"):
            env_lines.append(f"GRAPHRAG_EMBEDDING_KEY={config.get('api_key', '<YOUR_OPENAI_API_KEY>')}")
    elif config["llm_provider"] == "azure":
        env_lines.append(f"GRAPHRAG_API_KEY={config.get('api_key', '<YOUR_AZURE_KEY>')}")
        env_lines.append(f"AZURE_OPENAI_ENDPOINT={config.get('azure_endpoint', '<YOUR_AZURE_ENDPOINT>')}")
        if config["embedding_provider"] == "azure":
            env_lines.append(f"GRAPHRAG_EMBEDDING_KEY={config.get('api_key', '<YOUR_AZURE_KEY>')}")
    elif config["llm_provider"] == "ollama":
        env_lines.append("GRAPHRAG_API_KEY=ollama")

    if config["embedding_provider"] == "ollama_bge":
        env_lines.append("GRAPHRAG_EMBEDDING_KEY=ollama")
        env_lines.append(f"OLLAMA_BASE_URL={config.get('ollama_url', 'http://localhost:11434/v1')}")

    if config.get("domain_dictionary"):
        env_lines.append(f"GRAPHRAG_DOMAIN_DICTIONARY={config['domain_dictionary']}")

    env_path = os.path.join(output_dir, ".env")
    with open(env_path, "w") as f:
        f.write("\n".join(env_lines) + "\n")
    print(f"✅ Generated: {env_path}")


def main():
    parser = argparse.ArgumentParser(description="Generate GraphRAG settings.yaml")
    parser.add_argument("--config", required=True, help="JSON config file from installer")
    parser.add_argument("--output-dir", required=True, help="Project output directory")
    args = parser.parse_args()

    with open(args.config) as f:
        config = json.load(f)

    generate(config, args.output_dir)


if __name__ == "__main__":
    main()
